### ISSUE TITLE
[Feature] 增加 docker 挂载路径参数

### ISSUE THREAD

**Issue by lintmx** [MCSManager/Daemon#14]
**面板版本**
v1.3.0

**想法/建议**
实例配置增加 docker 挂载路径参数，当使用 docker 化部署 Daemon 时，如果 docker 内实例运行的工作目录与宿主机目录不一致或未挂载至宿主机时，将无法正确启动 docker 镜像。

**您认为这个想法/建议在每100人中会有多少人遇到/使用**
对于使用 docker 部署的人 80%

**Comment by lintmx** [comment]
这里可能是我没有描述好，目前我使用了 docker-compose 部署了 面板+前端+守护进程（将宿主机 docker.socket 挂载进 daemon），新建实例并且进程启动方式选择 docker 后发现无法正常启动实例，在 debug 后发现，实例启动时的挂载目录是配置中的工作目录，因为是 docker 部署的，这里的工作目录是在 docker 内的目录，但 docker run 是在宿主机发生的，宿主机中并没有该目录，所以导致了启动失败。我修改代码增加了一个宿主机的挂载目录配置后，实例才能够正常启动。

<img width="1024" alt="image" src="https://user-images.githubusercontent.com/10807435/153744350-b0ac56a8-c578-4735-8e64-d2b8f816ae30.png">
<img width="734" alt="image" src="https://user-images.githubusercontent.com/10807435/153744354-3b1c06c9-e1d2-45bd-a994-3d4eec47e003.png">
<img width="1148" alt="image" src="https://user-images.githubusercontent.com/10807435/153744367-08fdcfc2-38dd-492b-80d7-b1484c892709.png">

**Comment by lintmx** [comment]
修改的文件是 `src/entity/commands/docker/docker _start.ts`

**Comment by Suwings** [comment]
那你为什么不之间将你的`工作路径`的 `/app/data/InstanceData/....` 设置成 `/mnt/disk-3/repository/mcsmanager/.....` 这里呢？

照你第二张图，只要将工作路径`cwd`设置成你自己的挂载目录`dockerCwd`，不就行了吗，会报其他错误是吗，具体是什么错误？

**Comment by Suwings** [comment]
也就是说你希望指定 `/mnt/disk-3/repository/mcsmanager/.....` 到 `工作目录`，但是这个目录原先是不存在的，你希望启动服务器的适合自动创建这个目录，而不是提示工作目录并不存在，对吗？

**Comment by lintmx** [comment]
并不是，而是将工作目录和 docker 挂载目录区分开来，因为如果 daemon 是跑在 docker 内的，它所使用的工作目录和实例启动时挂载的目录是会不一致的。

**Comment by lintmx** [comment]
我贴一下我的运行环境吧：

docker-compose 文件目录：`/mnt/disk-3/repository/mcsmanager`

文件内容：
```
version: '3.3'

services:
  mcs:
    image: ghcr.io/lintmx/mcs:v9.2.0
    container_name: mcs
    restart: unless-stopped
    dns:
      - 10.11.12.1
    volumes:
      - ./mcs:/app/data
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.services.mcs.loadbalancer.server.port=23333"
      - "traefik.http.routers.mcs.rule=Host(`mcs.in.lintmx.com`) && PathPrefix(`/api`)"
      - "traefik.http.routers.mcs.tls=true"
      - "traefik.http.routers.mcs.tls.certresolver=le"
      - "traefik.http.routers.mcs.tls.domains[0].main=lintmx.com"
      - "traefik.http.routers.mcs.tls.domains[0].sans=*.in.lintmx.com"
      - "traefik.http.routers.mcs.middlewares=add-compress@file"
  mcs-daemon:
    #    image: ghcr.io/lintmx/mcs-daemon:v1.3.0
    image: mcs-daemon:test
    container_name: mcs-daemon
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./daemon:/app/data
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.services.mcs-daemon.loadbalancer.server.port=24444"
      - "traefik.http.routers.mcs-daemon.rule=Host(`mcs-daemon.in.lintmx.com`)"
      - "traefik.http.routers.mcs-daemon.tls=true"
      - "traefik.http.routers.mcs-daemon.tls.certresolver=le"
      - "traefik.http.routers.mcs-daemon.tls.domains[0].main=lintmx.com"
      - "traefik.http.routers.mcs-daemon.tls.domains[0].sans=*.in.lintmx.com"
      - "traefik.http.routers.mcs-daemon.middlewares=add-compress@file"
  mcs-ui:
    image: ghcr.io/lintmx/mcs-ui:v1.6.0
    container_name: mcs-ui
    restart: unless-stopped
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.services.mcs-ui.loadbalancer.server.port=80"
      - "traefik.http.routers.mcs-ui.rule=Host(`mcs.in.lintmx.com`) && !PathPrefix(`/api`)"
      - "traefik.http.routers.mcs-ui.tls=true"
      - "traefik.http.routers.mcs-ui.tls.certresolver=le"
      - "traefik.http.routers.mcs-ui.tls.domains[0].main=lintmx.com"
      - "traefik.http.routers.mcs-ui.tls.domains[0].sans=*.in.lintmx.com"
      - "traefik.http.routers.mcs-ui.middlewares=add-compress@file"

networks:
  traefik:
    external: true
```

所涉及到的 docker 镜像的 Dockerfile https://github.com/lintmx/containers
